from models.base import KBBIOBase
from sqlalchemy import Column, Integer, String, Float, Date, DateTime
from sqlalchemy.sql import func


class ShiprocketOrder(KBBIOBase):
    __tablename__ = 'shiprocket_orders'

    id = Column(Integer, primary_key=True, autoincrement=True)
    shiprocket_id = Column(String(50), nullable=False)
    channel_order_id = Column(String(50), nullable=True)
    shiprocket_created_at = Column(DateTime, nullable=True)
    invoice_no = Column(String(50), nullable=True)
    customer_name = Column(String(100), nullable=True)
    customer_email = Column(String(100), nullable=True)
    customer_phone = Column(String(20), nullable=True)
    customer_address = Column(String(255), nullable=True)
    customer_address_2 = Column(String(255), nullable=True)
    customer_city = Column(String(100), nullable=True)
    customer_state = Column(String(100), nullable=True)
    customer_pincode = Column(String(20), nullable=True)
    status = Column(String(50), nullable=True)
    payment_method = Column(String(50), nullable=True)
    item_name = Column(String(255), nullable=True)
    tax_percent = Column(Float, nullable=True)
    item_quantity = Column(Integer, nullable=True)
    item_net_price_excl_deduction = Column(Float, nullable=True)
    item_sp_excl_tax = Column(Float, nullable=True)
    item_disc_excl_tax = Column(Float, nullable=True)
    item_sp_incl_tax = Column(Float, nullable=True)
    item_disc_incl_tax = Column(Float, nullable=True)
    order_total = Column(Float, nullable=True)
    other_deduction = Column(Float, nullable=True)
    picked_up_date = Column(String(50), nullable=True)
    etd_date = Column(String(50), nullable=True)
    out_for_delivery_date = Column(String(50), nullable=True)
    delivered_date = Column(String(50), nullable=True)
    rto_initiated_date = Column(String(50), nullable=True)
    rto_delivered_date = Column(String(50), nullable=True)
    cod_charges = Column(Float, nullable=True)
    applied_weight_amount = Column(Float, nullable=True)
    freight_charges = Column(Float, nullable=True)
    charged_weight_amount = Column(Float, nullable=True)
    charged_weight_amount_rto = Column(Float, nullable=True)
    applied_weight_amount_rto = Column(Float, nullable=True)
    billing_amount = Column(Float, nullable=True)
    other_charges = Column(Float, nullable=True)
    giftwrap_charges = Column(Float, nullable=True)
    courier = Column(String(100), nullable=True)
    weight = Column(Float, nullable=True)
    dimensions = Column(String(100), nullable=True)
    applied_weight = Column(Float, nullable=True)
    charged_weight = Column(Float, nullable=True)
    pickedup_timestamp = Column(DateTime, nullable=True)
    awb = Column(String(100), nullable=True)
    delivery_executive_name = Column(String(100), nullable=True)
    rto_risk = Column(String(50), nullable=True)
    pickup_location = Column(String(100), nullable=True)
    created_at = Column(DateTime, server_default=func.now())